mybatis:
  type-aliases-package: com.hbwh.xj.myblog.bean
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?
      useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: test
    password: test
    
  thymeleaf:
    cache: false

  devtools:
    restart:
      trigger-file: trigger

pagehelper:
  helper-dialect: mysql

server:
  port: 9080

  
    
