mybatis:
  type-aliases-package: com.hbwh.xj.myblog.bean
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?
      useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: test
    password: test
    
  thymeleaf:
    cache: false

  devtools:
    restart:
      trigger-file: trigger

  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-wait: 5000ms
  config:
    additional-location: classpath:/addition.properties
    




pagehelper:
  helper-dialect: mysql

server:
  port: 9080
  servlet:
    session:
      timeout: 1200s

  
    
